const content = {
    instructions: {
        "Generate your": {
            english: "Generate your",
            french: "Générez votre",
            spanish: "Genera tu",
            italian: "Genera il tuo",
            german: "Generieren Sie Ihre",
        },
        "SUPER FAST": {
            english: "SUPER FAST",
            french: "SUPER RAPIDE",
            spanish: "SUPER RÁPIDO",
            italian: "SUPER VELOCE",
            german: "SUPERSCHNELL",
        },
        "Enter your info just": {
            english: "Enter your info just",
            french: "Entrez vos informations",
            spanish: "Introduce tu información sólo",
            italian: "Inserisci i tuoi dati solo",
            german: "Geben Sie Ihre Daten nur",
        },
        "once": {
            english: "once",
            french: "une seule fois",
            spanish: "una vez",
            italian: "una volta",
            german: "einmal ein",
        },
        "Then, create an Attestation in": {
            english: "Then, create an Attestation in",
            french: "Ensuite, créez une attestation en",
            spanish: "Entonces, crea una atestación en",
            italian: "Poi, creare un Attestato in",
            german: "Erstellen Sie dann eine Bescheinigung mit",
        },
        "one tap": {
            english: "one tap",
            french: "un seul clic",
            spanish: "un solo toque",
            italian: "un solo tocco",
            german: "einem Fingertipp",
        },
        "TOTAL PRIVACY": {
            english: "TOTAL PRIVACY",
            french: "CONFIDENTIALITÉ TOTALE",
            spanish: "PRIVACIDAD TOTAL",
            italian: "TOTALE PRIVACY",
            german: "GESAMTPRIVAT",
        },
        "Your info is": {
            english: "Your info is",
            french: "Vos informations sont",
            spanish: "Su información",
            italian: "Le vostre informazioni sono memorizzate",
            german: "Ihre Informationen werden nur auf Ihrem Gerät gespeichert und nie gesehen, verschickt oder an irgendjemanden verkauft",
        },
        "only": {
            english: "only",
            french: "uniquement",
            spanish: "sólo",
            italian: "solo",
            german: "",
        },
        "stored on": {
            english: "stored on",
            french: "stockées sur",
            spanish: "se almacena en",
            italian: "sul",
            german: "",
        },
        "your device": {
            english: "your device",
            french: "votre appareil",
            spanish: "su dispositivo",
            italian: "vostro apparecchio",
            german: "",
        },
        "and never seen, sent, or sold to": {
            english: "and never seen, sent, or sold to",
            french: "et ne sont jamais vues, envoyées ou vendues à",
            spanish: "y nunca visto, enviado o vendido a",
            italian: "e mai visto, spedito o venduto a",
            german: "",
        },
        "anyone": {
            english: "anyone",
            french: "personne",
            spanish: "nadie",
            italian: "nessuno",
            german: "",
        },
        "LET'S GO": {
            english: "LET'S GO",
            french: "ALLONS-Y",
            spanish: "VAMOS",
            italian: "ANDIAMO",
            german: "LOS GEHT'S",
        },        
    },
    myData: {
        "First Name": {
            english: "First Name",
            french: "Prenom",
            spanish: "Nombre",
            italian: "Nome",
            german: "Vorname",
        },
        "Last Name": {
            english: "Last Name",
            french: "Nom",
            spanish: "Apellido",
            italian: "Cognome",
            german: "Nachname",
        },
        "Birthdate": {
            english: "Birthdate",
            french: "Date de naissance",
            spanish: "Fecha de nacimiento",
            italian: "Data di nascita",
            german: "Geburtsdatum",
        },
        "Birthplace": {
            english: "Birthplace",
            french: "Lieu de naissance",
            spanish: "Lugar de nacimiento",
            italian: "Luogo di nascita",
            german: "Geburtsort",
        },
        "Address": {
            english: "Address",
            french: "Adresse",
            spanish: "Dirección",
            italian: "Indirizzo",
            german: "Adresse",
        },
        "City": {
            english: "City",
            french: "City",
            spanish: "Ciudad",
            italian: "Città",
            german: "Stadt",
        },
        "Postal Code": {
            english: "Postal Code",
            french: "Code postal",
            spanish: "Código postal",
            italian: "Codice postale",
            german: "Postleitzahl",
        },
        "Identity details are stored only on your device and never uploaded": {
            english: "Identity details are stored only on your device and never uploaded",
            french: "Les détails d'identité sont stockés localement et ne sont jamais transmis à personne",
            spanish: "Los detalles de identidad se almacenan sólo en su dispositivo y nunca se suben.",
            italian: "I dati identificativi sono memorizzati solo sul dispositivo e non vengono mai caricati",
            german: "Identitätsdaten werden nur auf Ihrem Gerät gespeichert und niemals hochgeladen",
        },
    },
    nav: {
        "Enter your info": {
            english: "Enter your info",
            french: "Entrez vos informations",
            spanish: "Introduce tu información",
            italian: "Inserisci i tuoi dati",
            german: "Geben Sie Ihre Informationen ein",
        },
        "Your Info": {
            english: "Your Info",
            french: "Vos informations",
            spanish: "Su información",
            italian: "Le vostre informazioni",
            german: "Ihre Informationen",
        },
        "Choose your reason to go out": {
            english: "Choose your reason to go out",
            french: "Choisissez votre raison de sortir",
            spanish: "Elija su razón para salir",
            italian: "Scegli il tuo motivo per uscire",
            german: "Wählen Sie Ihren Grund zum Ausgehen",
        },
        "Generating your attestation. Please check for it in your downloads.": {
            english: "Generating your attestation. Please check for it in your downloads.",
            french: "Génération de l'attestation.  Veuillez le vérifier dans vos téléchargements.",
            spanish: "Generando su certificado. Por favor, compruébelo en sus descargas.",
            italian: "Genera la tua attestazione. Si prega di controllare nei vostri download.",
            german: "Erstellung Ihrer Bescheinigung. Bitte überprüfen Sie dies in Ihren Downloads.",
        },
        "Sortir.io cannot generate an attestation in Facebook browser. Please visit Sortir.io in any other browser.": {
            english: "Sortir.io cannot generate an attestation in Facebook browser. Please visit Sortir.io in any other browser.",
            french: "Sortir.io ne peut pas générer une attestation dans le navigateur de Facebook. Veuillez consulter Sortir.io dans un autre navigateur.",
            spanish: "Sortir.io no puede generar un certificado en el navegador de Facebook. Por favor, visite Sortir.io en cualquier otro navegador.",
            italian: "Sortir.io non può generare un attestato nel browser di Facebook. Si prega di visitare Sortir.io in qualsiasi altro browser.",
            german: "Sortir.io kann keine Bescheinigung im Facebook-Browser erzeugen. Bitte besuchen Sie Sortir.io in einem anderen Browser.",
        },

    },
    reasons: {
        "Starting at": {
            english: "Starting at",
            french: "Heure de Sortie ",
            spanish: "A partir de",
            italian: "A partire da",
            german: "Beginnend bei",
        },
        ":": {
            english: ":",
            french: "h",
            spanish: ":",
            italian: ":",
            german: ":",
        },
        "Which reason should I choose?": {
            english: "Which reason should I choose?",
            french: "Quelle raison devrais-je choisir ?",
            spanish: "¿Qué razón debería elegir?",
            italian: "Quale motivo dovrei scegliere?",
            german: "Welchen Grund sollte ich wählen?",
        },
        "Back": {
            english: "Back",
            french: "Retour",
            spanish: "Volver",
            italian: "Indietro",
            german: "Zurück",
        }
    },
    sport: {
        "Exercise period": {
            english: "Exercise period",
            french: "Période du sport",
            spanish: "Periodo deportivo",
            italian: "Periodo dello sport",
            german: "Sportliche Periode",
        },
        "ends in": {
            english: "ends in",
            french: "se termine en",
            spanish: "termina en",
            italian: "finisce in",
            german: "endet in",
        },
        "starts in": {
            english: "starts in",
            french: "commence en ",
            spanish: "comienza en",
            italian: "inizia a",
            german: "beginnt in",
        },
        "Distance from home": {
            english: "Distance from home",
            french: "Distance de votre maison ",
            spanish: "Distancia de la casa",
            italian: "Distanza da casa",
            german: "Entfernung von zu Hause",
        },
        "Click to save your home GPS coordinates and stay within 1km": {
            english: "Click to save your home GPS coordinates and stay within 1km",
            french: "Cliquez pour enregistrer les coordonnées GPS de votre domicile et rester à moins d'un kilomètre",
            spanish: "Haga clic para guardar las coordenadas GPS de su casa y manténgase dentro de 1km",
            italian: "Clicca per salvare le coordinate GPS di casa e rimanere entro 1 km",
            german: "Klicken Sie hier, um Ihre GPS-Koordinaten zu speichern und innerhalb von 1 km zu bleiben.",
        },
        "I am home right now": {
            english: "I am home right now",
            french: "Je suis chez moi",
            spanish: "Estoy en casa ahora mismo",
            italian: "Sono a casa in questo momento",
            german: "Ich bin jetzt zu Hause.",
        },
        "Location data is not sent to anyone": {
            english: "Location data is not sent to anyone",
            french: "Les données de localisation ne sont transmis à personne",
            spanish: "Los datos de localización no se envían a nadie",
            italian: "I dati di localizzazione non vengono inviati a nessuno",
            german: "Standortdaten werden an niemanden gesendet",
        },
    }
}

export default content